name: Codacy Security Scan Branch 2

on:
  push:
    branches: [ master ]
  pull_request:
    
    branches: [ master ]
  schedule:
    - cron: '17 15 * * 4'

jobs:
  codacy-security-scan:
    name: Codacy Security Scan
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v2

      
      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@1.1.0
        with:
          
          
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          verbose: true
          output: results.sarif
          format: sarif
          
          gh-code-scanning-compat: true
          
          
          max-allowed-issues: 2147483647
